### ISSUE TITLE
Internal progress bar

### ISSUE THREAD

**Issue by ashkryab** [JideGuru/FileX#1]
After first run, app requests permission, after accept permission show up internal loading. After restart app all ok.

Try disable permission and run app.

**Comment by JideGuru** [comment]
Are you  running the release apk from codemagic or you cloned/built the project?

**Comment by ashkryab** [comment]
> Are you running the release apk from codemagic or you cloned/built the project?

From codemagic

**Comment by polilluminato** [comment]
I've got the exact same problem. Fresh install from Codemagic the app-release.apk after giving storage permission the app hangs with CircularProgressIndicator in the center of the screen.

If I kill the app and restart all work correctly. 
I think it's something in the lib/screens/splash.dart with permission_handler lib.

Device:
- Xiaomi Mi 6;
- Lineage OS 17.1 Android 10

**Comment by AdvaitKale01** [comment]
Any fixes for this issue?
On debugging the issue comes as context != null is not true

**Comment by AdvaitKale01** [comment]
On debugging the issue comes as context != null is not true

**Comment by yashbansal042** [comment]
Any updates on this?

**Comment by JideGuru** [comment]
@yashbansal042 This issue is fixed now. Pull the code from the master branch

**Comment by yashbansal042** [comment]
@JideGuru Thanks a lot for the update.
