### ISSUE TITLE
Crash in folder with photos

### ISSUE THREAD

**Issue by ashkryab** [JideGuru/FileX#2]
Are u use low resolution image in thumbnail on photo file? Very long loading, if fast swipe to down - scroll freezing and app crashing

Not usable

**Comment by JideGuru** [comment]
Thanks for the report. I will definitely look into this!

**Comment by ashkryab** [comment]
u can use https://pub.dev/packages/photo_manager . Plugin has thumbDataWithSize(width,height) function. This function get thumbnails from native cashed thumbs.

**Comment by ashkryab** [comment]
u can use https://pub.dev/packages/photo_manager . Plugin has thumbDataWithSize(width,height) function. This function get thumbnails from native cashed thumbs.


or if this blessing cannot be used, you can [compress images](https://pub.dev/packages/flutter_image_compress), then save the thumbnail in the [cache](https://pub.dev/packages/flutter_cache_manager), and before compressing check its presence in the cache, do not forget to increase the size of the cache. This will lead to a longer loading of photos on the screen (depends on the size of the image, maybe faster, but only if the image is not in the cache), but if you do this in separate isolations for each image, or in the same isolation if you organize a queue of compersion, this will not slow down the FPS

**Comment by vaishnavmhetre** [comment]
I didn't intend to raise and issue but had a query. How are you able to access **/storage/emulated/0**? Through path_provider directly? I'm getting **/storage/emulated/0/Android/data/_package_/**. Please note that this is received only when debugged, I haven't the tried building the app and then deploying.

Could you please help understand accessing the same?

**Comment by prateekmedia** [comment]
@JideGuru, cc @ashkryab Your Solution doesn't sync up well with the File Manager aspect as it still takes lots of time in image compression when done practically and a folder with 100 -150 photos it may also freeze the app, to prevent that kind of scenarios I have written image resize code which does the same without any extra libraries

```
switch (type) {
        case "image":
          return Container(
              width: 50,
              height: 50,
              child: Image(
                  errorBuilder: (b, o, c) {
                    return Icon(Icons.image);
                  },
                  image: ResizeImage(FileImage(File(file.path)), width: 50, height: 50)));
          break;

        case "video":
          return Conta....
```

It is from the file named as file_icon.dart

**Comment by prateekmedia** [comment]
I think this can be closed now as fixed in 
https://github.com/JideGuru/FileX/commit/74246e68d1a84db34908eacceced1fa1afc9e8ac#diff-3ac4c7d279f3573ce29213cd2ff1c76c057b50d7ef75e66721ab813cfa6d646cR129

**Comment by JideGuru** [comment]
@prateekmedia Im still testing, I'll close the issue after I'm done testing. Thanks
