### ISSUE TITLE
Unsupported operation: Platform._operatingSystem

### ISSUE THREAD

**Issue by laszukdawid** [JideGuru/FileX#22]
First of all, great work on this repository. I'm starting to learn dart/flutter but your project is quite close to what I'm planning to build so it's really helpful in learning.

I've just tried to clone your code and run it on Ubuntu 22.04 with the following version
```
$ flutter --version
Flutter 3.0.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f1875d570e (4 weeks ago) • 2022-07-13 11:24:16 -0700
Engine • revision e85ea0e79c
Tools • Dart 2.17.6 • DevTools 2.12.2
```

However, when running `flutter run -d chrome` or `flutter run -d linux` i'm getting the following exception:
```
The following UnsupportedError was thrown building Consumer<AppProvider>(dirty, dependencies:
[_InheritedProviderScope<AppProvider?>]):
Unsupported operation: Platform._operatingSystem

The relevant error-causing widget was:
  Consumer<AppProvider> Consumer:file:///home/user/projects/project/lib/app.dart:13:12

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49     throw_
dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                  _operatingSystem
dart-sdk/lib/io/platform_impl.dart 56:40                                         get operatingSystem
dart-sdk/lib/io/platform.dart 64:45                                              get _operatingSystem
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 839:8  get
dart-sdk/lib/io/platform.dart 153:47                                             get isIOS
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 839:8  get
packages/filex/app.dart 22:26                                                    <fn>
...
Another exception was thrown: Unsupported operation: Platform._operatingSystem
```

According to your Readme it's supposed to work on my machine. Any chance you could point at things to check? 

Any help really appreciated :)

**Comment by Joshokelola** [comment]
**Installation**
`dependencies:
  universal_platform: ^0.1.3`

Currently, if you include the dart.io.Platform anywhere in your code, your app will throw the following error on Web:
`Unsupported operation: Platform._operatingSystem`

With this plugin though you can perform platform detection on all platforms, including Web, without errors.

**Remove any usages of `dart.io.Platform` and replace with this:**
`import 'package:universal_platform/universal_platform.dart';`

Hope this helps @laszukdawid

**Comment by laszukdawid** [comment]
Thanks @Joshokelola , that helped! :)

For future noobs like me:
1) The `dart.io.Platform` reference is `Platform` class from `dart.io` namespace; to find it the best is to look for `Platform` and see if there's `import 'dart.io';` in the header. For *filex* specifically, these are in `/lib/app.dart` and `/lib/screens/settings.dart`.
2) To add `universal_platform` it needs to be manually added to `pubspec.yaml` and hopefully IDE helps with choosing version, or check https://pub.dev/packages/ for version. Then install using `flutter pub get` and replace all `Platform` -> `UniversalPlatform` with `import 'package:universal_platform/universal_platform.dart';` at the top.
