### ISSUE TITLE
Does this work in chrome or desktop (linux)?

### ISSUE THREAD

**Issue by laszukdawid** [JideGuru/FileX#23]
Hey, I'm trying to execute this project locally for web or desktop but it's one-step-at-a-time problem fixing. I'm a Flutter noob so it's likely I'm something doing wrong but thought that just in case I'd ask whether `FileX` is intended and was tested to run on `chrome` and `linux` devices?

Update:
I've just installed Android Studio and got it working with flutter. Seems that the same project is working fine there.

**Comment by JideGuru** [comment]
@laszukdawid FileX was built for the android OS. It won't work properly on chrome
